---
title: "Česko v Governance Report 2014"
---

```{r package-options, include=FALSE}
library(knitr)
opts_knit$set(root.dir='~/github/local/Charting-government/')
```

```{r Prep and load data, include=FALSE}
library(pbtools)
library(gridExtra)
library(pbtools)

file <- tempfile()
urldata <- 'http://www.governancereport.org/fileadmin/governancereport/2014/downloads/GovReportDataset2014.csv'
urlindex <- 'http://www.governancereport.org/fileadmin/governancereport/2014/downloads/GovRep2014Indexes.csv'
download.file(urldata,destfile='./data-input/GovReport2014_data.csv')
download.file(urlindex,destfile='./data-input/GovReport2014_index.csv')
GovReportIndex2014 <- read.csv('./data-input/GovReport2014_index.csv')
GovReportData2014 <- read.csv('./data-input/GovReport2014_data.csv')

countries <- c('Czech Republic','Poland','Slovakia','Hungary','Germany','Slovenia',
               'Estonia','Latvia','Lithuania','United Kingdom','New Zealand',
               'Netherlands')
```

```{r Documentation, include=FALSE}
# CODEBOOK AT
# http://www.governancereport.org/fileadmin/governancereport/2014/downloads/GovReportCodebook2014.pdf
# a5010: Degree of collaboration between ministries
# a5011: degree of coordination/collaboration within administrations
# a5075: Overall coherence of public policies
# a5072: Authorities capacity to adapt policies to changes in the 
# economic and social contexts
# a5071: Is evaluation a common practice?
# a5020: are actions of public authorities in line with a long-term strategic vision?
# a5022: do the pub auths have capacity to encourage public and private stakeholders to work
# towards that vision?
# a5040: are there public or private think tanks producing ...
# a5081: 'Is the capacity of national public authorities hampered by divisions within the State apparatus?'
# a5074: overall coherence
```

```{r Select variables, include=FALSE}
variables_indiv <- c('a5010','a5011','a5074','a5020',
                     'a5081','a5074','a5022','a5072')

# INDEXES CODEBOOK AT
# http://www.governancereport.org/fileadmin/governancereport/2014/downloads/IndexesCodebook.pdf
variables_index <- c('delivery_overallindex100','coordexpindex100','regqualindex100',
                     'intelligenceindex100')

# check that the country and variable names are correct in lists for filtering
sapply(countries, function(x) x %in% GovReportData2014$country)
sapply(variables_indiv, function(x) x %in% GovReportData2014$variable)
sapply(variables_index, function(x) x %in% GovReportData2014$variable)
```

```{r process index data, include=FALSE}
grr_i <- melt(GovReportIndex2014,id.vars = 'country') %>%
  filter(country %in% countries & variable %in% variables_index) %>%
  group_by(country) %>%
  mutate(mean = mean(value[variable!='delivery_overallindex100'])) %>%
  #   mutate(mean = mean(value,na.rm = T)) %>%
  ungroup() %>%
  dcast(country + mean ~ variable) %>%
  melt() %>%
  group_by(country) %>%
  mutate(mean = value[variable=='mean']) %>%
  ungroup() %>%
  group_by(variable) %>%
  arrange(-value)

grr_i$variable <- factor(grr_i$variable, levels=c('mean',
                                              'delivery_overallindex100',
                                              'intelligenceindex100',
                                              'coordexpindex100',
                                              'regqualindex100'))
grr_i$variable <- revalue(grr_i$variable, c('mean'='Průměr',
                                        'intelligenceindex100'='Analytická kapacita',
                                        'coordexpindex100'='Kvalita koordinace',
                                        'regqualindex100'='Kvalita regulace',
                                        'delivery_overallindex100'='Efektivita (výsledky)'))
variablesCZ <- c('Analytická kapacita','Kvalita koordinace',
                 'Kvalita regulace','Efektivita (výsledky)')
  
grr_i$alphaval <- .5
grr_i$alphaval[grr_i$countr=='Czech Republic'] <- 1
```

```{r Chart - produce, include=FALSE}

loadcustomthemes(ifgcolours,'Myriad Pro')
ggplot <- function(...) ggplot2::ggplot(...) +
  scale_fill_manual(values=themebasecolours) +
  scale_colour_manual(values=themebasecolours)

grr_iplots <- mapply(function(x, y) {
  grr_i2 <- grr_i[grr_i$variable==x,]
  grr_i2$country <- with(grr_i2, reorder(country,value))
  grr_iplot <- ggplot(grr_i2[grr_i2$variable==x,], aes(country, value,alpha=alphaval)) +
    geom_bar(stat='identity',position='dodge',fill=y) +
    scale_alpha_identity() +
    coord_flip() +
    scale_y_continuous(limits=c(0,100),breaks=c(0,25,50,75,100)) +
    theme(panel.grid.major.y=element_blank(),panel.grid.minor.x=element_line(),
          axis.text.y=element_text(size=12), plot.title=element_text(size=14)) +
    labs(title=x)
}, variablesCZ, themebasecolours[1:4], SIMPLIFY=FALSE)

args.list <- c(grr_iplots, 2,2)
names(args.list) <- c("plot1", "plot2", "plot3", 'plot4', "nrow", "ncol")
```

```{r Chart - display, echo=FALSE, warning=FALSE, message=FALSE}
do.call(grid.arrange, args.list)
```

```{r Process data - var level, include=FALSE, echo=FALSE}
grr_v <- melt(GovReportData2014,id.vars = 'country') %>%
  filter(country %in% countries & variable %in% variables_indiv) %>%
  group_by(country) %>%
  mutate(mean = mean(value[variable!='delivery_overallindex100'])) %>%
  #   mutate(mean = mean(value,na.rm = T)) %>%
  ungroup() %>%
  dcast(country + mean ~ variable) %>%
  melt() %>%
  group_by(country) %>%
  mutate(mean = value[variable=='mean']) %>%
  ungroup() %>%
  group_by(variable) %>%
  arrange(value)

variablesCZ_indiv <- c('Profesionalita','Nestrannost státní správy',
                 'Efektivita regulací','Regulace bez prodleni',
                 'Efektivita výběru daní','Schopnost zabraňovat daňovým únikům')
grr_v$variable <- revalue(grr_v$variable, c('mean'='Průměr',
                                        'proff'='Profesionalita',
                                        'impar'='Nestrannost státní správy',
                                        'X6.1'='Efektivita regulací',
                                        'X6.3'='Regulace bez prodleni',
                                        'a3032'='Efektivita výběru daní',
                                        'a3033'='Schopnost zabraňovat daňovým únikům'))
```

```{r Create chart - var level, echo=FALSE, include=FALSE}
  
grr_v$alphaval <- .5
grr_v$alphaval[grr$country=='Czech Republic'] <- 1

loadcustomthemes(ifgcolours,'Myriad Pro')

ggplot <- function(...) ggplot2::ggplot(...) +
  scale_fill_manual(values=themebasecolours) +
  scale_colour_manual(values=themebasecolours)

grrplots <- mapply(function(x, y) {
  grr_v2 <- grr_v[grr_v$variable==x,]
  grr_v2$value[is.na(grr_v2$value)] <- -200
  grr_v2$country <- with(grr_v2, reorder(country,value))
  grr_v2$textpos <- ifelse(grr_v2$value>0,grr_v2$value,0)+.1
  grr_vplot <- ggplot(grr_v2[grr_v2$variable==x,],
                      aes(country, value,alpha=alphaval)) +
    geom_bar(stat='identity',position='dodge',fill=y) +
    geom_text(aes(label=country,y=textpos),hjust=0,size=4) +
    scale_alpha_identity() +
    coord_flip() +
    scale_y_continuous(limits=c(-2,3),
                       breaks=c(-2,-1,0,1,2,3)) +
    theme(panel.grid.major.y=element_blank(),panel.grid.minor.x=element_line(),
          axis.text.y=element_blank(), plot.title=element_text(size=14)) +
    labs(title=x)
}, variablesCZ_indiv, themebasecolours[1:6], SIMPLIFY=FALSE)

args.list <- c(grrplots, 3, 2)
names(args.list) <- c(as.character(1:length(grrplots)), "nrow", "ncol")

```{r Display chart - var level}
do.call(grid.arrange, args.list)
